### ISSUE TITLE
Fix separating line between groups

### ISSUE THREAD

**Issue by kkdey** [kkdey/CountClust#14]
It seems the separating line between groups cuts through the middle of the bar. Probably we didn't see it before as number of samples was pretty large, but for small number of samples (30 for blakeley data), it seems to stand out.

check:

http://jhsiao999.github.io/singleCell-method/project/analysis/blakeley_classtpx.html

**Comment by jhsiao999** [comment]
Fixed. Now the demarcation is located between two sample bars.
