### ISSUE TITLE
The topic model takes too long to converge: is there a max no. of iterations?

### ISSUE THREAD

**Issue by kkdey** [kkdey/CountClust#25]
If you use the Github version of the package maptpx 

```
library(devtools)
install_github("kkdey/maptpx")
```

then you can choose the tmax as an option under control.

The default is tmax=10000

`out <- FitGoM(ex.counts, K=4, tol=100, control=list(tmax=100))`

**Comment by jhsiao999** [comment]
10,000 iterations take a long time. Are there any other ways around this?

**Comment by kkdey** [comment]
The default is 10,000 ....but you can set it to any value you want, see the example above for instance

**Comment by jhsiao999** [comment]
I understand. How about tolerance? Makes more sense to constraint on the
likelihood change that on the number of iterations.

**Comment by kkdey** [comment]
There is already a `tol` function for that, default to `tol=0.1`, meaning it stops when the log likelihood change between successive iterations is less than 0.1, you can change that too if you want to stop early

**Comment by jhsiao999** [comment]
What's the range of tol? Also does this define the percent decrease in
likelihood? For example, .1 is 10 percent decrease in likelihood.

**Comment by kkdey** [comment]
no it is stronger, it is the absolute change, not relative change in loglikelihood, the smaller the `tol`, the better it is, but also would take more time to converge.

**Comment by jhsiao999** [comment]
Okay let's add the definition to the function description. Thanks!
