### ISSUE TITLE
problem with large count matrix

### ISSUE THREAD

**Issue by sahyoun** [kkdey/CountClust#30]
Hi,

I was trying the clustering on a large matrix (5000 samples and 26000 genes). However, the 'FitGoM' function starts the computation and then stops with an error.

Here is the output that I get:

`FitGoM(t(d.counts), K=20, tol=0.1, path_rda="TCGA.FitGoM.rda") 
Fitting the topic model (due to Matt Taddy)
Estimating on a 5000 document collection.
Fit and Bayes Factor Estimation for K = 20
log posterior increase: Error in tpxEM(X = X, m = m, theta = theta, omega = Wfit, alpha = alpha,  :
  long vectors (argument 5) are not supported in .Fortran`

Does anyone have an idea what could be the problem?

**Comment by kkdey** [comment]
Can you please try to use the maptpx version on my Github page `kkdey/maptpx`, you can try the topics function then with the input parameter "method_admix=2", that should remove the dependency on Fortran support for the EM part.

**Comment by kkdey** [comment]
Now you can also use `Taddylab/maptpx` github R package. Future updates will be on this version.
