### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by davemcg** [kkdey/CountClust#31]
```
> library(CountClust)
Loading required package: ggplot2
Error : object ‘switch_axis_position’ is not exported by 'namespace:cowplot'
Error: package or namespace load failed for ‘CountClust’
>  sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X El Capitan 10.11.6

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_2.2.1

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9      gtools_3.5.0     assertthat_0.1   slam_0.1-40      grid_3.3.2       plyr_1.8.4       gtable_0.2.0     magrittr_1.5     scales_0.4.1     stringi_1.1.2    reshape2_1.4.2  
[12] lazyeval_0.2.0   cowplot_0.7.0    tools_3.3.2      stringr_1.1.0    munsell_0.4.3    colorspace_1.3-2 tibble_1.2      
```

**Comment by kkdey** [comment]
Hi, 

Is the version you have from the Github page or from Bioconductor? We have made some fixes to the one on Github, so if you are using the Bioconductor version, you can try `install_github("kkdey/Countclust")`, and try again. Let me know if that works !!

**Comment by chengarthur** [comment]
I met the same problem and use author's method to solve it .
it works! Thanks!
However, you need install package SQUAREM manually, the developers didn't mention it in the homepage.

**Comment by SaskiaFreytag** [comment]
Hi,

I tried to download the version from github but now it gives me the following error message:
Error: Could not find build tools necessary to build limma

Is it maybe not pointing to the right version of limma?

Cheers,

Saskia

**Comment by kkdey** [comment]
Hi, 

I reinstalled CountClust from Github and it seemed to be working. This is the sessionInfo() output, so I have the version `limma_3.30.13` it seems (sessionInfo run attached below).  I looked up the problem you mentioned online and found the following. Seems it may be an issue with Xcode or Rtools depending on the machine you are on.

http://stackoverflow.com/questions/38725060/error-could-not-find-build-tools-necessary-to-build-stringi-when-trying-devto

http://stackoverflow.com/questions/37776377/error-when-installing-an-r-package-from-github-could-not-find-build-tools-neces

Hoping this fixes the problem  :)

Kushal




> R version 3.3.3 (2017-03-06)
> Platform: x86_64-apple-darwin13.4.0 (64-bit)
> Running under: macOS Sierra 10.12
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] CountClust_0.1.2 ggplot2_2.2.1   
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.12.10         BiocInstaller_1.24.0 git2r_0.18.0         plyr_1.8.4          
>  [5] tools_3.3.3          digest_0.6.12        packrat_0.4.8-1      memoise_1.1.0       
>  [9] tibble_1.3.0         gtable_0.2.0         nlme_3.1-131         lattice_0.20-35     
> [13] mgcv_1.8-17          Matrix_1.2-8         curl_2.6             parallel_3.3.3      
> [17] cluster_2.0.6        withr_1.0.2          httr_1.2.1           stringr_1.2.0       
> [21] knitr_1.15.1         gtools_3.5.0         devtools_1.12.0      stats4_3.3.3        
> [25] grid_3.3.3           nnet_7.3-12          cowplot_0.7.0        R6_2.2.0            
> [29] maptpx_1.9-2         flexmix_2.3-14       limma_3.30.13        reshape2_1.4.2      
> [33] magrittr_1.5         MASS_7.3-45          scales_0.4.1         modeltools_0.2-21   
> [37] permute_0.9-4        picante_1.6-2        colorspace_1.3-2     ape_4.1             
> [41] stringi_1.1.5        lazyeval_0.2.0       munsell_0.4.3        slam_0.1-40         
> [45] vegan_2.4-3

**Comment by SaskiaFreytag** [comment]
Including the following command did indeed fix it:
options(buildtools.check = function(action) TRUE)

Thank you!

**Comment by kkdey** [comment]
Great ! glad to be of help.

**Comment by gowthamee** [comment]
I am facing difficulty installing the package "maptpx"  by the command install_github("TaddyLab/maptpx")

The command appears to run at first but gives the following error 
ERROR: compilation failed for package ‘maptpx’

Is there someone who faced a similar situation and succeeded ?   I am not familiar with compiling packages, so a detailed instruction or a link to such would be most helpful.

Thanks !!!
Gowthamee

I have copied the entire response below:

############################################################################
Downloading GitHub repo TaddyLab/maptpx@master
from URL https://api.github.com/repos/TaddyLab/maptpx/zipball/master
Installing maptpx
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/vf/rrm629q15qq6r3cn4xrth8sm0000gn/T/RtmpGQTHcS/devtools38d334292687/TaddyLab-maptpx-089f681'  \
  --library='/Library/Frameworks/R.framework/Versions/3.5/Resources/library' --install-tests 

* installing *source* package ‘maptpx’ ...
** libs
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include  -DRPRINT  -fPIC  -Wall -g -O2  -c latools.c -o latools.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include  -DRPRINT  -fPIC  -Wall -g -O2  -c rhelp.c -o rhelp.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include  -DRPRINT  -fPIC  -Wall -g -O2  -c topics.c -o topics.o
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o maptpx.so latools.o rhelp.o topics.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [maptpx.so] Error 1
ERROR: compilation failed for package ‘maptpx’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/maptpx’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/maptpx’
Installation failed: Command failed (1)

############################################################################

**Comment by kkdey** [comment]
Can you take a look if this solution works, it seems like a similar problem: https://github.com/kkdey/CountClust/issues/32.

**Comment by gowthamee** [comment]
Hi,
Following the instructions detailed for problem #32, solved the maptpx install issues. 

Thanks :)
Gowthamee
