### ISSUE TITLE
Error in tpxQ()

### ISSUE THREAD

**Issue by NagaComBio** [kkdey/CountClust#37]
Hello,

Was trying to run the GTEx example from the vignette and got the following error in tpxQ call. GTEx data looks good without any NAs.

```
> FitGoM(t(gtex.counts),
+ K=4, tol=0.1,
+ path_rda="GTExV6Brain.FitGoM.rda")
Fitting a Grade of Membership model
            (Taddy M., AISTATS 2012, JMLR 22,
            http://proceedings.mlr.press/v22/taddy12/taddy12.pdf)

Estimating on a 1259 samples collection.
Error in tpxQ(theta = theta, omega = omega, doc = X$i, wrd = X$j) : 
  NA/NaN/Inf in foreign function call (arg 8)
```

Part of sessionInfo()
````
other attached packages:
[1] CountClust_1.5.1    ggplot2_2.2.1       maptpx_1.9-4        GTExV6Brain_0.0.1   Biobase_2.34.0      BiocGenerics_0.20.0
[7] devtools_1.13.5 ```

**Comment by kkdey** [comment]
Sorry for the delayed response. I fixed the code - turned out it was a recent change in the slam package that broke it down. Can you please try reinstalling maptpx package [devtools::install_github("TaddyLab/maptpx") ] and try running it again. The version number of maptpx should be 1.9-5.

**Comment by NagaComBio** [comment]
Thanks for the fix it, it works now.
