### ISSUE TITLE
Getting identical results in multiple trials (num_trial > 1)

### ISSUE THREAD

**Issue by lijiang825** [kkdey/CountClust#40]
Hi, 

I am trying FitGoM on my single cell RNA-seq data and realized that I get identical results regarding log posterior increase, BF, and BIC when I set num_trial = 10 for FitGoM. I wonder if this means I didn't set randomization correctly, or the fitting converges quickly in each trial, or possibly a bug? Below is the result (three repeats are shown as an example):

options not specified: switching to default BIC, other choice is BF for Bayes factor

Fitting a Grade of Membership model
            (Taddy M., AISTATS 2012, JMLR 22,
            http://proceedings.mlr.press/v22/taddy12/taddy12.pdf)
Estimating on a 187 document collection.
Fit and Bayes Factor Estimation for K = 5
log posterior increase: 1563340, 144187.4, done.
log BF( 5 ) = 8585104.12

Fitting a Grade of Membership model
            (Taddy M., AISTATS 2012, JMLR 22,
            http://proceedings.mlr.press/v22/taddy12/taddy12.pdf)
Estimating on a 187 document collection.
Fit and Bayes Factor Estimation for K = 5
log posterior increase: 1563340, 144187.4, done.
log BF( 5 ) = 8585104.12

Fitting a Grade of Membership model
            (Taddy M., AISTATS 2012, JMLR 22,
            http://proceedings.mlr.press/v22/taddy12/taddy12.pdf)
Estimating on a 187 document collection.
Fit and Bayes Factor Estimation for K = 5
log posterior increase: 1563340, 144187.4, done.
log BF( 5 ) = 8585104.12

Many thanks,
Li Jiang

**Comment by kkdey** [comment]
@lijiang825 Are you using the version of maptpx from Github `https://github.com/kkdey/maptpx` or the CRAN version? It seems like it is running the same seed many times, which would be the case for the CRAN version.

**Comment by lijiang825** [comment]
Oh, I think I am using the default version of maptpx from cran, which is installed along with CountClust. I have installed the version from github and it solves the problem. Thanks so much for the quick response, really appreciate it.

**Comment by pcarbo** [comment]
@lijiang825 Thank you for your interest in CountClust, and for posting this issue. 

We are developing a new R package, [fastTopics](https://github.com/stephenslab/fastTopics), that has most of CountClust's features, plus several important improvements, most notabaly model fitting algorithms that are much faster and more accurate.

As this package is in active development, we welcome questions and feedback (on GitHub or by email).
