### ISSUE TITLE
Correct release versions (Bioconductor/CRAN, Bioconda/Conda-Forge)

### ISSUE THREAD

**Issue by epruesse** [kkdey/CountClust#41]
Hi @kkdey,

Could you advise on proper versions to use?

If I understand this right, the most current version of CountClust is in Bioconductor and thereby also available as Bioconda package. However, to work properly, CountClust needs a special version of `maptpx`, which is not the one on CRAN and therefore not the one packaged by Conda-Forge as `r-maptpx`. So the packages currently in Bioconductor and Bioconda will not work right out of the box. 

Would it be possible to make releases (tag the repos) for the correct, fully functional versions, so that the packages can be fixed?

ping @satriaps

**Comment by pcarbo** [comment]
@epruesse @satriaps Thank you for your interest in CountClust, and for posting this issue. 

We are developing a new R package, [fastTopics](https://github.com/stephenslab/fastTopics), that has most of CountClust's features, plus several important improvements, most notabaly model fitting algorithms that are much faster and more accurate.

As this package is in active development, we welcome questions and feedback (on GitHub or by email).
